### ISSUE TITLE
Previewer is not available

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/AvaloniaVSCode#40]
Running under macOS. The extension loads fine (see attached picture), and the XAML code completion works fine. However, the previewer is not available for AXAML files. 

The project is Avalonia `11.0.4` it's fully built. I tried restarting Visual Studio Code and had no luck.
![Screenshot 2023-09-04 at 13 18 39](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/assets/501613/526949e1-3e00-4009-bdd9-f15395818734)

Not sure if related, but every time I open VSCode I get:
```
Downloading the .NET Runtime.
AvaloniaTeam.vscode-avalonia wants to install .NET 7.0.10 but it already exists. No downloads or changes were made.
```

**Comment by prashantvc** [comment]
Could you try using the v0.0.18? 
You can download it from the release here https://github.com/AvaloniaUI/AvaloniaVSCode/releases/tag/v0.0.18

install it manually in the VS Code

**Comment by prashantvc** [comment]
This is should be fixed in latest version, please reopen if you continue to have an issue

**Comment by danipen** [comment]
@prashantvc sorry, it still happens in `0.0.18`:
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/501613/9bf128bb-0f55-43de-b35d-b7bda2069eed)
I'm using the latest version:
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/501613/4d38f46f-744e-4073-9979-90312666b856)

**Comment by prashantvc** [comment]
This is rather strange! Do you see the `Show Preview` command in the command palette? 
Make sure you have XAML file opened when you try to execute the command

<img width="872" alt="image" src="https://github.com/AvaloniaUI/AvaloniaVSCode/assets/328076/e7433c47-c701-4fb1-aa95-16130d0f3565">

**Comment by prashantvc** [comment]
Fixed in v0.0.20

**Comment by danipen** [comment]
It's not fixed in v0.0.20. Could you please reopening the issue?

**Comment by danipen** [comment]
Where can I find some logs or something that gives me a clue?

**Comment by danipen** [comment]
I can find these logs in the `Output` > `Avalonia Client` pane, but I'm afraid it doesn't give any clue:
```
2023-10-20 17:35:15.475 [info] Creating language service
2023-10-20 17:35:15.475 [info] Starting Avalonia Language Server...
2023-10-20 17:35:15.475 [info] [Trace - 17:35:15] Sending request 'initialize - (0)'.
2023-10-20 17:35:17.332 [info] [Trace - 17:35:17] Received response 'initialize - (0)' in 1984ms.
2023-10-20 17:35:17.332 [info] [Trace - 17:35:17] Sending notification 'initialized'.
2023-10-20 17:35:17.336 [info] [Trace - 17:35:17] Sending notification 'workspace/didChangeConfiguration'.
2023-10-20 17:35:17.444 [info] [Trace - 17:35:17] Received request 'client/registerCapability - (1)'.
2023-10-20 17:35:17.445 [info] [Trace - 17:35:17] Sending response 'client/registerCapability - (1)'. Processing request took 3ms
2023-10-20 17:35:17.445 [info] [Trace - 17:35:17] Sending notification 'textDocument/didOpen'.
2023-10-20 17:35:17.445 [info] [Trace - 17:35:17] Received request 'workspace/configuration - (2)'.
2023-10-20 17:35:17.446 [info] [Trace - 17:35:17] Sending response 'workspace/configuration - (2)'. Processing request took 0ms
2023-10-20 17:35:17.532 [info] [Trace - 17:35:17] Received request 'workspace/configuration - (3)'.
2023-10-20 17:35:17.532 [info] [Trace - 17:35:17] Sending response 'workspace/configuration - (3)'. Processing request took 1ms
2023-10-20 17:35:17.550 [info] [Trace - 17:35:17] Received request 'workspace/configuration - (4)'.
2023-10-20 17:35:17.550 [info] [Trace - 17:35:17] Sending response 'workspace/configuration - (4)'. Processing request took 0ms
2023-10-20 17:35:17.600 [info] [Trace - 17:35:17] Received notification 'window/logMessage'.
2023-10-20 17:35:17.600 [info] [Info  - 17:35:17] AvaloniaLanguageServer.Handlers.TextDocumentSyncHandler: ** DidOpenText: file:///Users/danipen/Projects/PreviewExample/MainWindow.axaml | Uri='file:///Users/danipen/Projects/PreviewExample/MainWindow.axaml'
2023-10-20 17:35:25.487 [info] [Trace - 17:35:25] Sending notification '$/setTrace'.
2023-10-20 17:35:26.972 [info] [Trace - 17:35:26] Sending notification '$/setTrace'.
```

**Comment by danipen** [comment]
@prashantvc any progress on this issue? Thanks!

**Comment by BinToss** [comment]
I'm experiencing a similar issue. Or the same issue. It's hard to tell.
The command to open the previewer wasn't available in the editor buttons or the Command Center so I bound a hotkey to it.
Using a hotkey to trigger `avalonia.showPreviewToSide` resulted in the following prompt:
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/7243190/38aa8e76-6912-4cbb-82c2-0692b800a8d6)

Clicking `Build` works. Dotnet build the solution and the assets are generated, but `avalonia.showPreviewToSide` still can't find the previewer assets.

```pwsh
2023-12-11 07:08:54.605 [info] Previewer assets are not available.
2023-12-11 07:08:57.643 [info] [EXT - INFO] Solution data path path: C:\Users\Noah\AppData\Local\Temp\GroupBox.Avalonia.sln.json
2023-12-11 07:08:57.710 [info] parser process args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"dotnet "c:\Users\Noah\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.25\solutionParserTool\SolutionParser.dll" "c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia.sln" --sdk 7.0"
2023-12-11 07:08:58.210 [info] parser process exited 0
2023-12-11 07:08:58.593 [info]   Determining projects to restore...

2023-12-11 07:08:59.052 [info]   All projects are up-to-date for restore.

2023-12-11 07:09:00.331 [info]   Could not extract the MVID from "obj\Debug\net6.0\refint\GroupBox.Avalonia.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:00.331 [info]   GroupBox.Avalonia -> c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia\bin\Debug\net6.0\GroupBox.Avalonia.dll

2023-12-11 07:09:00.395 [info]   Could not extract the MVID from "obj\Debug\net7.0\refint\GroupBox.Avalonia.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:00.395 [info]   GroupBox.Avalonia -> C:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia\bin\Debug\net7.0\GroupBox.Avalonia.dll

2023-12-11 07:09:01.292 [info]   Could not extract the MVID from "obj\Debug\net8.0\refint\GroupBox.Avalonia.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:01.295 [info]   GroupBox.Avalonia -> c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia\bin\Debug\net8.0\GroupBox.Avalonia.dll

2023-12-11 07:09:02.548 [info]   Could not extract the MVID from "obj\Debug\net8.0\refint\GroupBox.Avalonia.Sample.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:02.549 [info]   GroupBox.Avalonia.Sample -> c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia.Sample\bin\Debug\net8.0\GroupBox.Avalonia.Sample.dll

2023-12-11 07:09:02.568 [info]   Could not extract the MVID from "obj\Debug\net7.0\refint\GroupBox.Avalonia.Sample.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:02.569 [info]   GroupBox.Avalonia.Sample -> c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia.Sample\bin\Debug\net7.0\GroupBox.Avalonia.Sample.dll

2023-12-11 07:09:03.211 [info]   Could not extract the MVID from "obj\Debug\net6.0\refint\GroupBox.Avalonia.Sample.dll". Are you sure it is a reference assembly?

2023-12-11 07:09:03.212 [info]   GroupBox.Avalonia.Sample -> c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia.Sample\bin\Debug\net6.0\GroupBox.Avalonia.Sample.dll

2023-12-11 07:09:03.232 [info] 

2023-12-11 07:09:03.233 [info] Build succeeded.

2023-12-11 07:09:03.234 [info]     0 Warning(s)

2023-12-11 07:09:03.234 [info]     0 Error(s)

2023-12-11 07:09:03.234 [info] 

2023-12-11 07:09:03.235 [info] Time Elapsed 00:00:04.84

2023-12-11 07:09:03.393 [info] [EXT - INFO] Solution data path path: C:\Users\Noah\AppData\Local\Temp\GroupBox.Avalonia.sln.json
2023-12-11 07:09:03.458 [info] parser process args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"dotnet "c:\Users\Noah\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.25\solutionParserTool\SolutionParser.dll" "c:\Repos\BinToss\GroupBox.Avalonia\GroupBox.Avalonia.sln" --sdk 7.0"
2023-12-11 07:09:04.019 [info] Previewer assets generated at 
2023-12-11 07:09:04.019 [info] Command avalonia.previewProcess, file:///c%3A/Repos/BinToss/GroupBox.Avalonia/GroupBox.Avalonia.Sample/MainWindow.axaml
2023-12-11 07:09:04.019 [info] Previewer assets are not available.
2023-12-11 07:09:04.031 [info] parser process exited 0
```

**Comment by BinToss** [comment]
https://github.com/AvaloniaUI/AvaloniaVSCode/blob/main/src/vscode-avalonia/src/commands/createPreviewerAssets.ts#L37
`const output`'s properties are all empty strings.
`generatePreviewerAssets` was called with the following args:
```json
  "projectPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\GroupBox.Avalonia.Sample.csproj"
```
```json
{
  "name": "GroupBox.Avalonia.Sample",
  "path": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\GroupBox.Avalonia.Sample.csproj",
  "targetPath": "",
  "outputType": "WinExe",
  "designerHostPath": "",
  "targetFramework": "",
  "depsFilePath": "",
  "runtimeConfigFilePath": "",
  "projectReferences": [
    "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\GroupBox.Avalonia\\GroupBox.Avalonia.csproj"
  ],
  "directoryPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample",
  "intermediateOutputPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\obj\\Debug\\Avalonia\\references"
}
```

`targetFramework` is undefined when a project multi-targets frameworks.

**Comment by prashantvc** [comment]
I am sorry to here you are hitting this issue. I am going to take a look on priority

**Comment by BinToss** [comment]
I dug into AvaloniaVSCode and AvaloniaVS over the past few weekends. After learning a bit more about the projects in question, I've updated my previous comment with corrections, trace notes, and suggestions.

**Comment by BinToss** [comment]
Authors of similar extensions are requesting easier access–or documentation of existing access–to the ms-dotnettools extensions' 'current' solution file and parsed projects. I spent last week and weekend looking through the existing ms-dotnettools extensions' exports for this data and ways to be notified of when data in the [project system](https://github.com/dotnet/project-system) updates (e.g. OnChanged events). From what I've learned, the current implementation intends for API users to communicate with a so-called 'brokered service'. This might be refer to the Roslyn host process. Or it may refer to the project system host process. The CSharp and CsDevKit extensions each provide different functions and variables related to 'servers' and the symbol names do not make their purpose clear.

**Comment by prashantvc** [comment]
This should be fixed in v0.0.27, please reopen the issue if you continue to see this

**Comment by BinToss** [comment]
@danipen Does v0.0.27 resolve your issue? The issue persists on my end.

**Comment by danipen** [comment]
The issue persist on my end too. Using `Avalonia for VSCode v0.0.28`. cc/ @prashantvc

**Comment by mikson022** [comment]
![Screenshot_2024-01-24_19-29-14](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/125257322/e93fc49c-a3fd-4d04-9ab3-e52c6fdee4f0)
Using Debian based distro, I have the same issue with previewer. Clicking build does nothing, however, I can build and run manually, any help?

**Comment by BinToss** [comment]
@mikson022, post the contents of the `$TMPDIR/avalonia.log` and `$TMPDIR/$solutionName.json`. Those will help determine the cause of the issue.

**Comment by BinToss** [comment]
@mikson022, post the contents of the `$TMPDIR/avalonia.log` and `$TMPDIR/$solutionName.json`. Those will help determine the cause of the issue.

Try the following in bash:
```bash
if [ -n "${TMPDIR}" ]
then
  echo "Printing contents of $TMPDIR/avalonia.log"
  cat $TMPDIR/avalonia.log
  echo "enter the filename of your .sln sans the .sln extension e.g. 'mySolution' when the solution file is mySolution.sln"
  solutionName=read # prompts for user input
  echo "Printing contents of $TMPDIR/$solutionName.json:"
  cat $TMPDIR/$solutionName.json
else
  echo "environment variable TMPDIR is undefined. Env vars are..."
  printenv
fi
```

**Comment by prashantvc** [comment]
reopening this!

**Comment by mikson022** [comment]
> Try the following in bash:
> 
> ```shell
> if [ -n "${TMPDIR}" ]
> then
>   echo "Printing contents of $TMPDIR/avalonia.log"
>   cat $TMPDIR/avalonia.log
>   echo "enter the filename of your .sln sans the .sln extension e.g. 'mySolution' when the solution file is mySolution.sln"
>   solutionName=read # prompts for user input
>   echo "Printing contents of $TMPDIR/$solutionName.json:"
>   cat $TMPDIR/$solutionName.json
> else
>   echo "environment variable TMPDIR is undefined. Env vars are..."
>   printenv
> fi
> ```
> 
> (I'm not at my desk atm; writing and testing this script in Termux was miserable)

environment variable TMPDIR is undefined. Env vars are...
SHELL=/bin/bash
SESSION_MANAGER=local/MX-HP:@/tmp/.ICE-unix/3166,unix/MX-HP:/tmp/.ICE-unix/3166
WINDOWID=96469833
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_MENU_PREFIX=xfce-
QT_LOGGING_RULES=qt.qpa.xcb.warning=false
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXOggbwa/agent.3166
DESKTOP_SESSION=xfce
SSH_AGENT_PID=3266
GTK_MODULES=canberra-gtk-module:gail:atk-bridge
XDG_SEAT=seat0
PWD=/home/Mikson/Desktop/C#/Automation/MineMate
LOGNAME=Mikson
XDG_SESSION_DESKTOP=xfce
QT_QPA_PLATFORMTHEME=gtk2
XDG_SESSION_TYPE=x11
XAUTHORITY=/home/Mikson/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/Mikson
GDM_LANG=en_US.UTF-8
HOME=/home/Mikson
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
XDG_CURRENT_DESKTOP=XFCE
VTE_VERSION=7006
QT_PLATFORMTHEME=gtk2
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=Mikson
DISPLAY=:0.0
SHLVL=1
XDG_VTNR=7
XDG_SESSION_ID=1
PAPERSIZE=letter
XDG_RUNTIME_DIR=/run/user/1000
QT_PLATFORM_PLUGIN=gtk2
XDG_DATA_DIRS=/usr/share/xfce4:/home/Mikson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
GDMSESSION=xfce
DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-GJE93Fqv91,guid=53acc489a33e639e4bce6b8965b2bdae
QT_SCALE_FACTOR=1
_=/usr/bin/printenv

**Comment by BinToss** [comment]
You don't have an environment variable for the system or user temporary directories, so we'll do this differently. Avalonia's extension is one of the few that allows VSCode users to click its "open log file" button.
In VSCode, Open `Output` (CTRL+ALT+O), use the `Switch Output` menu to switch to `Avalonia Client`, and then click the `Open 
Log Output File` button.

Paste the log contents in a code block like so:
````
```
2024-01-29 16:05:48.376 [info] Creating language service
2024-01-29 16:05:48.434 [info] Starting Avalonia Language Server...
2024-01-29 16:05:49.119 [info] [Trace - 4:05:49 PM] Sending request 'initialize - (0)'.
2024-01-29 16:05:57.867 [info] [Trace - 4:05:57 PM] Received response 'initialize - (0)' in 8748ms.
2024-01-29 16:05:57.867 [info] [Trace - 4:05:57 PM] Sending notification 'initialized'.
2024-01-29 16:05:57.872 [info] [Trace - 4:05:57 PM] Sending notification 'workspace/didChangeConfiguration'.
2024-01-29 16:05:58.344 [info] [Trace - 4:05:58 PM] Received request 'client/registerCapability - (1)'.
2024-01-29 16:05:58.345 [info] [Trace - 4:05:58 PM] Sending response 'client/registerCapability - (1)'. Processing request took 2ms
2024-01-29 16:05:58.369 [info] [Trace - 4:05:58 PM] Received request 'workspace/configuration - (2)'.
2024-01-29 16:05:58.369 [info] [Trace - 4:05:58 PM] Sending response 'workspace/configuration - (2)'. Processing request took 0ms
2024-01-29 16:05:58.419 [info] [Trace - 4:05:58 PM] Received request 'workspace/configuration - (3)'.
2024-01-29 16:05:58.419 [info] [Trace - 4:05:58 PM] Sending response 'workspace/configuration - (3)'. Processing request took 0ms
2024-01-29 16:09:36.713 [info] [Trace - 4:09:36 PM] Sending request 'shutdown - (1)'.
2024-01-29 16:09:36.825 [info] [Trace - 4:09:36 PM] Received response 'shutdown - (1)' in 165ms.
2024-01-29 16:09:36.825 [info] [Trace - 4:09:36 PM] Sending notification 'exit'.
2024-01-29 16:09:36.826 [info] Language client stopped
2024-01-29 16:09:50.417 [info] Creating language service
2024-01-29 16:09:51.261 [info] Starting Avalonia Language Server...
2024-01-29 16:09:51.281 [info] [Trace - 4:09:51 PM] Sending request 'initialize - (0)'.
2024-01-29 16:09:54.848 [info] [Trace - 4:09:54 PM] Received response 'initialize - (0)' in 3567ms.
2024-01-29 16:09:54.848 [info] [Trace - 4:09:54 PM] Sending notification 'initialized'.
2024-01-29 16:09:55.829 [info] [Trace - 4:09:55 PM] Sending notification 'workspace/didChangeConfiguration'.
2024-01-29 16:09:56.608 [info] [Trace - 4:09:56 PM] Received request 'client/registerCapability - (1)'.
2024-01-29 16:09:56.608 [info] [Trace - 4:09:56 PM] Sending response 'client/registerCapability - (1)'. Processing request took 2ms
2024-01-29 16:09:56.770 [info] [Trace - 4:09:56 PM] Received request 'workspace/configuration - (2)'.
2024-01-29 16:09:56.770 [info] [Trace - 4:09:56 PM] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
2024-01-29 16:09:58.335 [info] [Trace - 4:09:58 PM] Received request 'workspace/configuration - (3)'.
2024-01-29 16:09:58.335 [info] [Trace - 4:09:58 PM] Sending response 'workspace/configuration - (3)'. Processing request took 0ms
2024-01-29 16:11:43.404 [info] [Trace - 4:11:43 PM] Sending request 'shutdown - (1)'.
2024-01-29 16:11:43.506 [info] [Trace - 4:11:43 PM] Received response 'shutdown - (1)' in 148ms.
2024-01-29 16:11:43.506 [info] [Trace - 4:11:43 PM] Sending notification 'exit'.
2024-01-29 16:11:43.512 [info] Language client stopped
2024-01-29 16:11:53.393 [info] Creating language service
2024-01-29 16:11:53.800 [info] Starting Avalonia Language Server...
2024-01-29 16:11:53.824 [info] [Trace - 4:11:53 PM] Sending request 'initialize - (0)'.
2024-01-29 16:11:58.311 [info] [Trace - 4:11:58 PM] Received response 'initialize - (0)' in 4488ms.
2024-01-29 16:11:58.312 [info] [Trace - 4:11:58 PM] Sending notification 'initialized'.
2024-01-29 16:11:59.362 [info] [Trace - 4:11:59 PM] Sending notification 'workspace/didChangeConfiguration'.
2024-01-29 16:11:59.900 [info] [Trace - 4:11:59 PM] Received request 'client/registerCapability - (1)'.
2024-01-29 16:11:59.901 [info] [Trace - 4:11:59 PM] Sending response 'client/registerCapability - (1)'. Processing request took 2ms
2024-01-29 16:12:00.071 [info] [Trace - 4:12:00 PM] Received request 'workspace/configuration - (2)'.
2024-01-29 16:12:00.072 [info] [Trace - 4:12:00 PM] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
2024-01-29 16:12:01.355 [info] [Trace - 4:12:01 PM] Received request 'workspace/configuration - (3)'.
2024-01-29 16:12:01.356 [info] [Trace - 4:12:01 PM] Sending response 'workspace/configuration - (3)'. Processing request took 0ms

```
````

Next, we need the parsed solution details. Run "Avalonia: Create previewer assets". The first line will contain the path we need. Open that file path and paste its contents into a JSON-syntax code block e.g.
````
```json
{
  "solution": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.sln",
  "projects": [
    {
      "name": "GroupBox.Avalonia",
      "path": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia\\GroupBox.Avalonia.csproj",
      "targetPath": "",
      "outputType": "Library",
      "designerHostPath": "",
      "targetFramework": "",
      "targetFrameworks": [
        "net6.0",
        "net7.0",
        "net8.0"
      ],
      "depsFilePath": "",
      "runtimeConfigFilePath": "",
      "projectReferences": [],
      "directoryPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia",
      "intermediateOutputPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia\\obj\\Debug\\Avalonia\\references"
    },
    {
      "name": "GroupBox.Avalonia.Sample",
      "path": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\GroupBox.Avalonia.Sample.csproj",
      "targetPath": "",
      "outputType": "WinExe",
      "designerHostPath": "",
      "targetFramework": "",
      "targetFrameworks": [
        "net6.0",
        "net7.0",
        "net8.0"
      ],
      "depsFilePath": "",
      "runtimeConfigFilePath": "",
      "projectReferences": [
        "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\GroupBox.Avalonia\\GroupBox.Avalonia.csproj"
      ],
      "directoryPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample",
      "intermediateOutputPath": "c:\\Repos\\BinToss\\GroupBox.Avalonia\\GroupBox.Avalonia.Sample\\obj\\Debug\\Avalonia\\references"
    }
  ],
  "files": []
}
```
````

**Comment by tofferteves** [comment]
I'm not familiar in this, but after troubleshooting a bit, I found that inside the previewerProcess command , the _**const previewParams**_ is always undefined.  

It seems the workspace state is not really getting updated no matter what is done even after building the project or running it.

`export class PreviewerProcess implements Command {
	id: string = util.AppConstants.previewProcessCommandId;

	async execute(mainUri?: vscode.Uri): Promise<PreviewerData> {
		util.logger.appendLine(`Command ${this.id}, ${mainUri}`);
		let result: PreviewerData = { file: mainUri! };
		const previewParams = this._context.workspaceState.get<PreviewerParams>(util.AppConstants.previewerParamState);    // this line always returns undefined
		if (previewParams && mainUri) {
			result = await this.startPreviewerProcess(previewParams, mainUri);
		}

		return result;
	}`



If I force to execute the command previewerAssetsCommand inside the ShowPreviewToSideCommand before anything else

	public async execute(mainUri?: vscode.Uri, allUris?: vscode.Uri[]) {
		const activeFile = mainUri ?? vscode.window.activeTextEditor?.document.uri;
		await vscode.commands.executeCommand(AppConstants.previewerAssetsCommand);   // test to force update the workspace
		let previewerData = this._processManager.getPreviewerData(activeFile?.toString() ?? "");

		if (!previewerData) {
			previewerData = await vscode.commands.executeCommand<PreviewerData>(
				AppConstants.previewProcessCommandId,
				activeFile
			);
		}

Then the preview works successfully. I only tested this on MacOS.

**Comment by lukewire129** [comment]
I had a similar type of day to this one.
Finally solved it.
I'm guessing it's something similar to mine.
Same thing, no "Show preview" and no preview icon.
But here's how it looks for me right now.
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/54387261/89ac7755-223b-44e3-a3ca-e3c431f171ce)

---
Here's how I solved it.

1. Look at the bottom area of the VS Code window (Select Language Mode). 

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/54387261/59888c82-4d9e-4c80-836f-70ff13895bea)

2. Click on it and type 'Avalonia xaml' to change it.
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/54387261/637c845f-ca91-4049-8c22-0de588920a11)

**Before**
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/54387261/391f2267-f559-49bf-931d-2b3bff4a6ad7)

**After**
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/54387261/a0cfe105-0ac2-4391-abbc-7649944fa65a)

**Comment by Kefaku** [comment]
I had a similar issue. For some reason, despite the extension description saying

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/114934849/d31dc53c-2a72-488f-8901-1875123feaee)

after also installing dotnet sdk 7.0 it now works.

**Comment by BinToss** [comment]
The C# source code was updated to require .NET 8, but the DLLs included with the avalonia-vscode haven't been updated in ages. The C# side of this extension has had build errors since...last year? It's trying to call AvaloniaVS method signatures that don't exist and never have.

**Comment by Lumberj4cked** [comment]
Has there been any progress on this yet?

I have the same issue on VSCode version 1.19.2 on Arch Linux with Dotnet SDK's 7.0.120 and 8.0.401 and Avalonia extension v0.0.31.

I cannot view my previews, but building and running the application works fine.

**Comment by BinToss** [comment]
> Has there been any progress on this yet?
> 
> I have the same issue on VSCode version 1.19.2 on Arch Linux with Dotnet SDK's 7.0.120 and 8.0.401 and Avalonia extension v0.0.31.
> 
> I cannot view my previews, but building and running the application works fine.

I started working on a fix in January, but I had to set it aside after spending over a month on it. There are/were several root causes of this issue.

**Comment by szwenni** [comment]
For me a quick fix (windows) was also to edit the solutionParser.js (extensionFolder/out/solutionParser.js)
in the parseSolution function I updated the function which call the dll to look like this
```
const previewer = (0, child_process_1.spawn)(`dotnet`, [parserLocation.putInQuotes(), '-s', '7.0.400', solutionPath.putInQuotes()], {
            windowsVerbatimArguments: false,
            env: process.env,
            shell: true,
        });
```

Where the 7.0.400 is the 7.x version taken from the command dotnet --list-sdks
You need a 7.x installed otherwise it will not work, at least I don't got it working.

**Comment by Advanium** [comment]
> You need a 7.x installed otherwise it will not work, at least I don't got it working.

This is my first time trying to use Avalonia. I followed the installation steps for v11 and got the app building and running via the console. Wanted to modify some views in vs code and preview the view using this extension, which lead me to this same issue.

I have both SDK version 7 and 8 installed on my machine, and created a fresh x-plat project which by default targets .NET 8.

When I try to run the SolutionParser providing SDK version 7, I get the error that there is no `net8.0-browser` target. This is correct as it was introduced with .NET 8.

When run with SDK version 8, it also fails due to the fact that the SolutionParser itself was built against .NET 7.

Does the parser have to be built against .NET 8 or did I make a mistake?

**Comment by Advanium** [comment]
I got it working for v0.0.31 on my Windows machine with latest .NET 8.0 SDK installed by swapping out the SolutionParser files:

1. Have the latest .NET 8.0 SDK installed.
2. Go to `%userprofile%\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\solutionParserTool` and move all files to a backup folder.
3. Clone the https://github.com/prashantvc/SolutionParser repository.
4. Build the SolutionParser project using `dotnet build -c release`.
5. Copy the build output to the `%userprofile%\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\solutionParserTool` folder.

**Comment by heartacker** [comment]
Anybody? Make a pr and file a release

**Comment by nadevko** [comment]
I have similar issues. I'm using NixOS unstable with .NET 8.0.403. The funniest thing is that the previewer works right after creating a project. However, the "Build" button on the `Previewer is not available. Build the project first.` notification simply dismisses the message instead of opening the preview.

```plain
2024-11-27 22:22:47.509 [info] Command avalonia.previewProcess, file:///home/user/Example/1/App/Views/Main.axaml
2024-11-27 22:22:47.510 [info] Previewer assets are not available.
2024-11-27 22:22:49.271 [info] [EXT - INFO] Solution data path path: /tmp/Example1.sln.json```

**Comment by wl2776** [comment]
> I got it working for v0.0.31 on my Windows machine with latest .NET 8.0 SDK installed by swapping out the SolutionParser files:

On Linux it solves the issue only partially.

After updating SolutionParser to the head of the Github repository, Preview viewer doesn't demand to build project, but throws exception "System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform."

* OS: Ubuntu 24.04
* Avalonia for VSCode: 0.0.31
* Solution parser: 
   ```
   commit d4b200860bdb2de2fbc4480b2dd1ab46876edc27 (HEAD -> main, origin/main, origin/HEAD)
   Author: Julien Lebosquain <julien@lebosquain.net>
   Date:   Fri Dec 20 18:40:07 2024 +0100
   ```

**Comment by SyntaxFisher** [comment]
I encountered the following issue on macOS while using the Avalonia extension in VS Code:

The "Build the project first" popup persisted in the previewer, even though the project was successfully built, and the application could run without issues. The logs showed that the previewer assets were not available, and the parser process exited with an error. Specifically, the Avalonia extension's SolutionParser was unable to correctly locate or process the .sln file and associated project files. This meant that the necessary metadata for the previewer could not be generated, preventing the preview from displaying. This was similar to the issue described by @BinToss, where the extension could not locate or process the previewer assets.

The issue stemmed from the outdated SolutionParser.dll used by the Avalonia extension. This older version could not handle newer project configurations or target frameworks correctly, leading to errors when generating and recognizing previewer assets. For instance, it failed to parse modern .csproj files and did not account for updated paths or framework specifications required by .NET 9 projects.

To fix this, first, I cloned the `SolutionParser` repository from [prashantvc/SolutionParser](https://github.com/prashantvc/SolutionParser):
```
git clone https://github.com/prashantvc/SolutionParser.git
cd SolutionParser
dotnet build -c release
```
The rebuild `SolutionParser.dll`was located in `bin/Release/net9.0`. I replaced the existing files in the Avalonia extension directory:
```
cd ~/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31/solutionParserTool
mkdir ../backup
mv * ../backup/
cp -r ~/SolutionParser/bin/Release/net9.0/* .
rmdir net9.0
```

After these steps, the previewer started working correctly. The build popup only appeared the first time and after that, "Build" completed successfully, and the previewer assets were properly recognized.
