### ISSUE TITLE
Previewer not working in Linux.

### ISSUE THREAD

**Issue by stevekallal** [AvaloniaUI/AvaloniaVSCode#61]
I see another dev is having issues with the .AXAML previewer in Linux (issue #58), so I'm not alone. My distro is MX Linux which is Debian based and closer to pure Debian than the Ubuntu family. My desktop environment is XCFE4.

I'm relatively new with Linux as a development platform. The Windows version of this extension works mostly okay with a few hiccups that I can deal with. But it stubbornly will NOT render the layout under my Linux desktop. That is the preview pane stays blank. The same .AXAML previews under Windows.

Notice the contributing guidelines recommend .NET Core 7.0, which I have installed. Yet for some reason the dotnet command line tools create a 6.0 version instead. Also I get my extensions from the VS Code marketplace (v0.0.20) and don't compile my own, not yet. So my extension is NOT compiled from GitHub.

Hopefully we can find a solution. Worse case scenario is I'll have to use Windows to design my UI layouts.

**Comment by prashantvc** [comment]
duplicate of #58

**Comment by prashantvc** [comment]
@stevekallal 
I have pushed the fix in v0.0.21, could you give it a try and let me know if it works for you?

**Comment by ZN0N15** [comment]
> @stevekallal I have pushed the fix in v0.0.21, could you give it a try and let me know if it works for you?

Hi, I'm also currently facing the same issues on my Archlinux machine. After trying both v0.0.21 and v0.0.22 I can confirm that it didn't seem to fix the issues for me. Previewer still doesn't show anything, not even a build project prompt. Autocompletions also still don't work at all for some reason.

![screenshot2023-10-31-11:37:04](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/57549197/cc57a138-ee84-45ff-9159-572945d75fc9)

**Comment by prashantvc** [comment]
This should be fixed in the v0.0.27. Please reopen the issue if you continue to see this
