### ISSUE TITLE
Can't get past "Build the project first."

### ISSUE THREAD

**Issue by UdoGu** [AvaloniaUI/AvaloniaVSCode#81]
### Describe the bug

When I open an axaml-file in the VSCode editor and click "Show preview" or use the command "Avalonia: Show preview" a notification pops up to build the project first. Needless to say that I have build already. However clicking the "Build" button on the notification popup or using the command "Avalonia: Create previwer assets" creates the following entries in the log (see below).

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/19910483/b718434c-42d8-4075-b0d4-18bafb04d78a)

Looks like it can't find the correct sln-file. Though it's just one folder above the opened axaml-file. Needless to say that my workspace contains more than just one solution. For me it looks very random. First creating a temporary json file in the users temp dir and then trying to use a random sln-file. 

NOTE: It's always the same *.axaml-file to preview, but the parser looks for different sln-files for every preview attempt. Unfortunately never the correct one.

Anybody know what's going on here?

### To Reproduce

Having a workspace with several solutions.

### Avalonia for VS Code

0.0.25

### Avalonia version

11.0.2

### VS Code version

1.85.0

### Relevant log output

```shell
2023-12-12 06:28:20.351 [info] parser process exited 4294967295
```

**Comment by BinToss** [comment]
I believe this extension should implement and sync a "Current/Opened Solution" value with the Solution the user opened with the official C# extension.

**Comment by TcPirate1** [comment]
I have encountered this as well. My versions are the same as OP's and for what it's worth `dotnet sdk is 8.0.100`

**Comment by prashantvc** [comment]
Extension require you to install .NET Core 7, could you give another try after installing it

**Comment by TcPirate1** [comment]
> Extension require you to install .NET Core 7, could you give another try after installing it

This has indeed solved my issue. I was silly and didn't realize I only had the runtimes.

**Comment by prashantvc** [comment]
Fixed in v0.0.26

**Comment by ShinQdan** [comment]
> Fixed in v0.0.26

Not really fixed, at least for me. With version 0.0.26 installed I still get the log:
`2024-01-09 12:44:03.485 [info] parser process args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"dotnet "c:\Users\shin\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.26\solutionParserTool\SolutionParser.dll" "e:\code\test\avalonia-test\testApp" --sdk 7.0"
2024-01-09 12:44:03.684 [info] parser process exited 4294967295`
So it seems it still wants to use .NET 7.0.
I even reinstalled the extension and created new project to check if it works, but it doesn't.

**Comment by BinToss** [comment]
@ShinQdan That was fixed in https://github.com/AvaloniaUI/AvaloniaVSCode/commit/721efcfac53e198d1668b6972ddb70be42d73ce7 of https://github.com/AvaloniaUI/AvaloniaVSCode/releases/tag/v0.0.28
